version: '3.3'

services:
  db-wordpress:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wp_mici_bnsr

  wordpress:
    depends_on:
      - db-wordpress
    image: wordpress:5.8.2-php7.3-apache
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db-wordpress:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: somewordpress
      WORDPRESS_DB_NAME: wp_mici_bnsr
      WORDPRESS_DEBUG: 1
    working_dir: /var/www/html
    volumes: # this is where we tell Docker what to pay attention to
      - ../wp-content/:/var/www/html/wp-content/

volumes:
  db_data: {}
